import:
  - tsx
require:
  - source-map-support/register
  - src/test/helpers/mocha-bootstrap.js
  - src/test/helpers/registerLoaders.js
timeout: 1000
recursive: true
node-options:
  - "experimental-specifier-resolution=node"
